import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import type { Session, User } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

export type Profile = {
  sno: number;
  /** Login handle, e.g. "mervik1703". Generated by the database. */
  user_id: string | null;
  auth_uid: string | null;
  first_name: string;
  last_name: string | null;
  email_id: string;
  dob: string | null;
  is_admin: boolean;
  is_approved: boolean;
  is_owner: boolean;
  created_at: string;
};

export function fullName(p: Profile | null): string {
  if (!p) return "";
  return [p.first_name, p.last_name].filter(Boolean).join(" ").trim();
}

/**
 * "schema-missing" means the auth migration has not been applied to the Supabase
 * project yet. It is kept distinct from a plain error so the UI can tell the
 * operator what to run instead of showing a generic failure.
 */
export type AuthStatus = "loading" | "signed-out" | "pending" | "ready" | "schema-missing";

type AuthResult = { ok: boolean; error?: string };

/** Mirrors the NOT NULL columns on tesoro_users that the signup trigger reads. */
export type SignUpDetails = {
  firstName: string;
  lastName: string;
  dob: string;
};

type Ctx = {
  status: AuthStatus;
  session: Session | null;
  user: User | null;
  profile: Profile | null;
  isAdmin: boolean;
  /** `identifier` is an email address or a login handle. */
  signIn: (identifier: string, password: string) => Promise<AuthResult>;
  signUp: (email: string, password: string, details: SignUpDetails) => Promise<AuthResult>;
  signOut: () => Promise<void>;
  reloadProfile: () => Promise<void>;
};

const AuthCtx = createContext<Ctx | null>(null);

/**
 * Supabase auth errors surface as terse strings that don't tell the reader what
 * to do about them, and several are project-configuration problems rather than
 * anything the person typed.
 */
function friendlyAuthError(message: string): string {
  const m = message.toLowerCase();

  if (m.includes("rate limit") || m.includes("too many requests")) {
    return "Supabase's built-in email service has hit its hourly limit. Turn off “Confirm email” in Supabase → Authentication → Sign In / Providers → Email, or wait an hour and try again.";
  }
  if (m.includes("email not confirmed")) {
    return "This email hasn't been confirmed yet. Open the link Supabase sent you, or turn off “Confirm email” in the Supabase auth settings.";
  }
  if (m.includes("invalid login credentials")) {
    return "That email or user ID and password don't match.";
  }
  if (m.includes("already registered") || m.includes("already been registered")) {
    return "An account with this email already exists — sign in instead.";
  }
  if (m.includes("signups not allowed") || m.includes("signup is disabled")) {
    return "Sign-ups are disabled for this Supabase project.";
  }
  return message;
}

/** PostgREST reports an unknown table/function as 42P01, or 404 via PGRST202. */
function isMissingSchema(code?: string, message?: string): boolean {
  if (code === "42P01" || code === "PGRST202" || code === "PGRST205") return true;
  const m = (message || "").toLowerCase();
  return m.includes("does not exist") || m.includes("could not find the table");
}

export function AuthProvider({ children }: { children: ReactNode }) {
  const [session, setSession] = useState<Session | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [isAdmin, setIsAdmin] = useState(false);
  const [schemaMissing, setSchemaMissing] = useState(false);
  const [resolving, setResolving] = useState(true);

  const loadProfile = useCallback(async (userId: string) => {
    // The role lives on the profile row itself; RLS pins is_admin/is_approved
    // so a user cannot raise their own privileges by editing it.
    const { data, error } = await supabase
      .from("tesoro_users")
      .select("*")
      .eq("auth_uid", userId)
      .maybeSingle();

    if (error && isMissingSchema(error.code, error.message)) {
      setSchemaMissing(true);
      setProfile(null);
      setIsAdmin(false);
      return;
    }

    const row = (data as Profile | null) ?? null;
    setSchemaMissing(false);
    setProfile(row);
    // The owner is always an admin, mirroring is_tesoro_admin() in the database.
    setIsAdmin(Boolean(row?.is_admin) || Boolean(row?.is_owner));
  }, []);

  useEffect(() => {
    let active = true;

    // Register the listener before the initial getSession so a token refreshed
    // mid-flight is not missed.
    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((_event, nextSession) => {
      if (!active) return;
      setSession(nextSession);

      if (!nextSession?.user) {
        setProfile(null);
        setIsAdmin(false);
        setResolving(false);
        return;
      }

      // Supabase deadlocks if another supabase-js call is awaited inside this
      // callback, so the profile fetch is deferred to a fresh task.
      setResolving(true);
      setTimeout(() => {
        if (!active) return;
        loadProfile(nextSession.user.id).finally(() => {
          if (active) setResolving(false);
        });
      }, 0);
    });

    supabase.auth.getSession().then(({ data }) => {
      if (!active) return;
      setSession(data.session);
      if (!data.session?.user) {
        setResolving(false);
        return;
      }
      loadProfile(data.session.user.id).finally(() => {
        if (active) setResolving(false);
      });
    });

    return () => {
      active = false;
      subscription.unsubscribe();
    };
  }, [loadProfile]);

  /**
   * Accepts either an email address or a login handle. Supabase Auth only
   * authenticates by email, so a handle is resolved through the
   * email_for_login RPC first.
   */
  const signIn = useCallback(async (identifier: string, password: string): Promise<AuthResult> => {
    const entered = identifier.trim();
    let email = entered;

    if (!entered.includes("@")) {
      const { data, error } = await supabase.rpc("email_for_login", {
        _identifier: entered,
      });
      if (error) {
        return isMissingSchema(error.code, error.message)
          ? { ok: false, error: "User ID sign-in isn't set up yet. Run the auth migration." }
          : { ok: false, error: error.message };
      }
      if (!data) {
        return { ok: false, error: "No account found with that user ID." };
      }
      email = data as unknown as string;
    }

    const { error } = await supabase.auth.signInWithPassword({ email, password });
    return error ? { ok: false, error: friendlyAuthError(error.message) } : { ok: true };
  }, []);

  const signUp = useCallback(
    async (email: string, password: string, details: SignUpDetails): Promise<AuthResult> => {
      const { error } = await supabase.auth.signUp({
        email: email.trim(),
        password,
        options: {
          emailRedirectTo: `${window.location.origin}/`,
          // Read by the handle_new_user trigger to populate tesoro_users.
          data: {
            first_name: details.firstName.trim(),
            last_name: details.lastName.trim(),
            dob: details.dob,
          },
        },
      });
      return error ? { ok: false, error: friendlyAuthError(error.message) } : { ok: true };
    },
    [],
  );

  const signOut = useCallback(async () => {
    await supabase.auth.signOut();
    setProfile(null);
    setIsAdmin(false);
    // Collections are cached per browser; leaving them would leak the previous
    // user's cars into the next sign-in on a shared machine.
    try {
      for (const key of Object.keys(localStorage)) {
        if (key.startsWith("dg.cars")) localStorage.removeItem(key);
      }
    } catch {
      // Storage may be unavailable (private mode); nothing to clean up then.
    }
  }, []);

  const reloadProfile = useCallback(async () => {
    if (session?.user) await loadProfile(session.user.id);
  }, [session, loadProfile]);

  const status = useMemo<AuthStatus>(() => {
    if (resolving) return "loading";
    if (!session?.user) return "signed-out";
    if (schemaMissing) return "schema-missing";
    // The owner account never waits for approval.
    if (!profile?.is_approved && !profile?.is_owner) return "pending";
    return "ready";
  }, [resolving, session, schemaMissing, profile]);

  const value = useMemo<Ctx>(
    () => ({
      status,
      session,
      user: session?.user ?? null,
      profile,
      isAdmin,
      signIn,
      signUp,
      signOut,
      reloadProfile,
    }),
    [status, session, profile, isAdmin, signIn, signUp, signOut, reloadProfile],
  );

  return <AuthCtx.Provider value={value}>{children}</AuthCtx.Provider>;
}

export function useAuth(): Ctx {
  const v = useContext(AuthCtx);
  if (!v) throw new Error("useAuth must be used inside <AuthProvider>");
  return v;
}
