// GENERATED FILE — do not edit by hand.
// Rebuilt with: node scripts/gen-taxonomy.mjs
//
// The vocabulary of an established collection, so a brand-new account is not
// asked to invent one. Every list is ordered by how often the value actually
// occurs, which is what makes the first few options in a dropdown the useful
// ones. Models are the base name only — "Skyline", not "Nissan Skyline" and not
// "Skyline GT-R" — because the trim belongs in the variant, and a model list
// that repeats the make you just chose wastes the whole dropdown.
//
// Keys are lowercased for lookup; the values keep their display spelling.

export const MAKES: string[] = [
  "Ford",
  "Fantasy",
  "Pop Culture",
  "Toyota",
  "Nissan",
  "Porsche",
  "Chevrolet",
  "BMW",
  "Mercedes Benz",
  "Honda",
  "Lamborghini",
  "Ferrari",
  "Dodge",
  "Aston Martin",
  "Jeep",
  "Audi",
  "Volkswagen",
  "Mazda",
  "MBX",
  "McLaren",
  "Land Rover",
  "Subaru",
  "Jaguar",
  "Mitsubishi",
  "Pontiac",
  "Tesla",
  "Alfa Romeo",
  "Hyundai",
  "Lotus",
  "Bentley",
  "Bugatti",
  "DMC",
  "Fiat",
  "GMC",
  "Ducati",
  "Maserati",
  "Cadillac",
  "Pagani",
  "Range Rover",
  "Citroen",
  "Renault",
  "Suzuki",
  "Volvo",
  "Austin",
  "Lexus",
  "Batmobile",
  "Datsun",
  "Triumph",
  "Plymouth",
  "RAM",
  "Lancia",
  "InGen",
  "Acura",
  "Buick",
  "RBPT - Ford",
  "Mini",
  "Masito",
  "Monster Truck",
  "Lincoln",
  "Polaris",
  "Pierce",
  "Shelby",
  "Alpine",
  "Koenigsegg",
  "Isuzu",
  "MAN",
  "Polestar",
  "W Motors",
  "Plymoth",
  "Skidster",
  "Scania",
  "Ground Grinder",
  "Blaze Blaster III",
  "Aero Lift",
  "Hummer",
  "Kousiku Hauler",
  "Peugeot",
  "Boeing",
  "Airbus",
  "Freightliner",
  "Intrenational",
  "Helicopter",
  "Delivery Truck",
  "Fendt 209 Varlo",
  "LNER",
  "Deutz-Fahr",
  "Massey Ferguson",
  "Seven Plank",
  "Piaggio",
  "Maisto",
  "Panther",
  "Auburn",
  "McMurtry",
  "Gordon Murray Automotive",
  "Delorean",
  "Williams",
  "Lucid",
  "Super Rigs",
  "Road Roller",
  "Rover",
  "Land Cruiser",
  "Rimac",
  "Dacia",
  "Batman",
  "Second Story Lorry",
  "Custom",
  "Sakura Sprinter",
  "Opel",
  "Racing Convoy",
  "Nitro Rail",
  "Hype Hauler",
  "Speed Blaster",
  "Transformers",
  "Hudson",
  "Hirohata",
  "Mario",
  "Luigi",
  "Horizon Hauler",
  "Radical",
  "Sherp",
  "Terra-Torque",
  "Retro Rig",
  "Automibili Pikinfarina",
  "F-35 B",
  "Spaceshuttle",
  "Airblade",
  "Western Star",
  "Trabant",
  "Holden",
  "Alpha",
  "International",
  "Abarth",
  "Cirrus",
  "Cessna",
  "Lockheed Martin",
  "UPS",
  "Morris",
  "DHL",
  "Fossil",
  "Speed Racer",
  "Celica",
  "Pontoon",
  "Hino",
  "Rob'N",
  "Fleet Flyer",
  "Greenwood",
  "Fleet Street",
  "Motorcycle",
  "Autocar",
  "Unreleased",
  "Hotwheels",
];

export const COLOURS: string[] = [
  "Red",
  "White",
  "Blue",
  "Black",
  "Green",
  "Silver",
  "Yellow",
  "Orange",
  "Grey",
  "Purple",
  "Unknown",
  "Gold",
  "Beige",
  "Brown",
  "Maroon",
  "Pink",
  "Chrome",
  "Gray",
  "Teal",
  "Rainbow",
  "Sandal",
  "Yelow",
  "Brige",
  "NA",
];

export const TYPES: string[] = [
  "Sports Car",
  "SUV",
  "Muscle",
  "Super Car",
  "Fantasy",
  "Pickup Truck",
  "Sedan",
  "Hatchback",
  "Van",
  "Race Car",
  "Motorcycle",
  "Formula Car",
  "Grand Tourer",
  "Rally Car",
  "Transporter",
  "Roadster",
  "Truck",
  "Convertable",
  "Batmobile",
  "Aeroplane",
  "Classic Car",
  "Trailer",
  "Construction",
  "Clip",
  "Wagon",
  "Helicopter",
  "Fire Truck",
  "Hot Rod",
  "Pop Culture",
  "Tow Truck",
  "Tractor",
  "Monster Truck",
  "ATV",
  "RC Car",
  "Hyper Car",
  "Mariokart",
  "Working Rig",
  "Ambulance",
  "Low Rider",
  "Luxury Car",
  "Train Engine",
  "Auto Rikshaw",
  "Concept",
  "Boat",
  "Saloon",
  "Buggy",
  "Firetruck",
  "School Bus",
  "Forklift",
  "Crop Combine",
  "Open Wagon",
  "Gasser",
  "Trashtruck",
  "Flintmobile",
  "Road Roller",
  "Estate",
  "Executive",
  "Train",
  "Custom Car",
  "Dump Truck",
  "Bus",
  "Excavator",
  "Flatbed",
  "Trash Truck",
  "Fire Ladder",
  "Crop Sprayer",
  "Convertible",
  "Raft",
  "Jetsons Capsule",
  "Garbage Truck",
  "NA",
];

export const BRANDS: string[] = [
  "Hotwheels",
  "Matchbox",
  "Mini GT",
  "Majorette",
  "Disney",
  "CCA",
  "Tomica",
  "Pop Race",
  "Maisto",
  "Jada",
  "Takara Tomy",
  "Greenlight",
  "Bburago",
  "Thomas",
  "Kaido House",
  "97M",
  "Siku",
  "Teamsterz",
  "Detsky",
  "Jams",
  "Star Race",
  "Time Micro",
  "Ghost Player",
  "Trends Hobby",
  "GCD Model",
  "Johnny Lightning",
  "Phantom Knight",
  "Tarmac Works",
  "Happy Car",
  "GFCC",
  "More Arts",
  "Mortal Model",
  "Original Model",
  "Motor Helix",
  "Top Lux",
  "CM Model",
];

export const ASSORTMENTS: string[] = [
  "Mainline",
  "Premium",
  "Box",
  "Silver Series",
  "Blister",
  "5 Pack",
  "Replica",
  "Moving Parts",
  "Team Transport",
  "Working Rigs",
  "Qube Carz",
  "Sky Busters",
  "2 Pack",
  "Nano Rides",
  "Collection",
  "Track Fleet",
  "6 Pack",
  "Deluxe",
  "Street Cars",
  "Metal",
  "Diorama",
  "4 Pack",
  "Highway Haulers",
  "Monster Trucks",
  "Tuning",
  "Frame",
  "Trailer",
  "Super Rigs",
  "Playset",
  "Elite 64",
];

export const SIZES: string[] = ["1:64", "1:55", "1:87", "1:43", "'1:64", "1:36", "02:04"];

export const SERIES: string[] = [
  "Fast & Furious",
  "Car Culture",
  "Cars",
  "Matchbox The Movie",
  "Team Transport",
  "Showroom",
  "Pop Culture",
  "Boulevard",
  "James Bond",
  "Liberty Walk",
  "WR 2026",
  "Vintage",
  "Vintage Club",
  "Pantone",
  "Tooned",
  "F1",
  "Mustang 60",
  "Audi",
  "JDM Legends",
  "Screen Time",
  "Experimotors",
  "Motor Show",
  "BMW",
  "Racing",
  "Porsche",
  "Collection",
  "Jurassic World",
  "Gran Tourismo",
  "Batman",
  "Back to the Future",
  "Then And Now",
  "Indiana Jones",
  "AO Racing",
  "Mercedes Benz",
  "Track Fleet",
  "Streets of Japan",
  "Hollywood",
  "Camel Trophy",
  "Zamac",
  "Dirt",
  "Toyota",
  "HW Hot Rods",
  "Batmobile",
  "National Icons",
  "Hybrid Speed",
  "Pontiac",
  "Rally Racers",
  "Performance Trucks",
  "Italian Roads",
  "Jeep",
  "British Roadways",
  "Convertible Dreams",
  "MBX OFF Road",
  "Ferrari",
  "Exotics",
  "Motorcycle Club",
  "Race Day",
  "City",
  "Honda Diorama Set",
  "Race Verse",
  "Mijo Exclusive",
  "Diorama",
  "Rescue",
  "Track Aces",
  "Hot Trucks",
  "Truckin' Along",
  "Top Secret",
  "Nismo",
  "Korean Exclusive",
  "Veilside",
  "Tuning",
  "Moto",
  "Thomas",
  "WRC",
  "EV",
  "Seven Eleven",
  "Dream Garage",
  "Ultra Hots",
  "Lambo & Lancia",
  "SUV",
  "Aston Martin & Lambo",
  "DC",
  "Mariokart",
  "Ford",
  "Kuma",
  "Dex",
  "Police",
  "Alain Prost 1988",
  "Compact Kings",
  "5 Pack",
  "Hot Truck",
  "Metro",
  "Art Cars",
  "Drop Tops",
  "Muscle Mania",
  "Battalion 64",
  "Final Edition",
  "Factory Fresh",
  "Pit Set",
  "Off Road",
  "Harry Potter",
  "Gravity",
  "Mod Shop",
  "Marvel",
  "Senna",
  "Castheads",
  "Night Speeed",
  "Presentation",
  "NDDP Racing",
  "Mattel",
  "Isle of Man",
  "25th Anniversary",
  "Ronin",
  "All Drivers Welcome",
  "UPS",
  "Need For Speed",
  "Vielside",
  "RE-Amemiya",
  "Corvettte Racing",
  "Petersen Museum",
  "Mizu Design",
  "Liberty Works",
  "Chip Hart Racing",
  "Camping Set",
  "Ride-Ons",
  "Exoticars",
  "D-Max Racing",
  "xDrive",
  "Garuda",
  "DHL",
  "Speed Racer",
  "Spoon",
  "Charles Leclerc's Wedding Getaway Car",
  "New Giallo Orion",
  "Boss",
  "Magnus Racing",
  "Khul Racing",
  "GVR Motorsport",
  "GT Championship",
  "Wall Racing",
  "Wayne Taylor Racing",
  "DHL Electric",
  "Compack Kings",
  "RSR Turbo 2.1",
  "British Trans-American Expedition",
  "Rallye Monte Carlo",
  "Pandem",
  "Ducktail",
  "Apple",
  "Verde Selvans",
  "RS 2.7",
  "Coca Cola",
];

export const SUB_SERIES: string[] = [
  "Mix 1",
  "2025",
  "Mix 2",
  "Clip",
  "2026",
  "83 - 85",
  "2018",
  "Wallmart Exclusive",
  "Batmobile",
  "Brian O'Conner",
  "2026 Mix 1",
  "80 - 82",
  "92 - 94",
  "Toy Story",
  "89 - 91",
  "95 - 97",
  "Disney Pixar 100",
  "Villians",
  "Short Card",
  "Thrill Climbers",
  "Tokyo Drift",
  "126 - 130",
  "Terra Trek",
  "2024",
  "141 - 145",
  "2026 Mix 2",
  "Power Trip",
  "151 - 155",
  "Race Off",
  "Euro Speed",
  "Modern Classics",
  "146 - 150",
  "Brian O'Conner Diorama",
  "Movie Heroes",
  "Villian Pursuit",
  "Aero Styles",
  "Mix 3",
  "Road Trip",
  "2026 Mix 4",
  "2026 Mix 3",
  "Anniversary",
  "Timeless Icons",
  "156 - 160",
  "Circuit Legends",
  "Vintage Racing",
  "HW Off Road",
  "LeMans Set",
  "Barbie",
  "131 - 135",
  "For your eyes only",
  "Super Silhoutte",
  "The Italian Job",
  "Jurassic World",
  "Stranger Things",
  "Classic TV Series",
  "The Simpsons",
  "Gran Tourismo",
  "Spectre 007",
  "Spectre",
  "2023 Super GT Series",
  "2025 Mix 4",
  "Skeleton Rexy",
  "Skyfall",
  "Liberty Walk",
  "Thunderball",
  "Kenmeri",
  "LB Works Type 1, Ver 1",
  "LB Works Type 1, Ver 2",
  "Casino Royale",
  "Japanese GP 2nd Place",
  "The Living Daylights",
  "The Spy Who Loved me",
  "Fortune7",
  "Gold Tooth Rexy",
  "HW Getaway",
  "Monopoly",
  "Transformers",
  "Minions",
  "Back to the Future",
  "Hotwheels 80th Anniversary",
  "Scooby Doo",
  "Godzilla",
  "Matrix",
  "The Rugrats",
  "Peanuts",
  "The Batman",
  "2024 Mix 2",
  "Black Widow",
  "The Dark Knight",
  "Series 5",
  "Rexy",
  "Roxy",
  "James Bond",
  "Mariokart",
  "2025 Mix 1",
  "Cultuyre Beavis and Butt-Head",
  "Dumb & Dumber",
  "MTV",
  "Spider Man",
  "Deadpool Scooter",
  "Seasonal Livery 2025",
  "Japan GP 2025",
  "Silhoutte Works",
  "The World is not enough",
  "Die Another Day",
  "Kuma",
  "CRS Version",
  "Part 2",
  "Japan Historics",
  "The Rookie",
  "The Godfather",
  "Red Chrome",
  "No Time to die",
  "Diamonds are Forever",
  "Most Wanted",
  "LB Works",
  "Combat V-I",
  "Abas Works IZTK",
  "Matsukiyo Koku 3",
  "Sumatra Cswoboda Kmentel Win",
  "Super Silhoutte, Auto Finesse SEMA 2023",
  "Super Silhoutte, LP Presentation",
  "Airwolf",
  "The Good Dinosaur",
  "Forza",
  "Onwards",
  "822",
  "MBX County",
  "LeMans 24H",
  "Gold Finger",
  "Tomorrow Never Dies",
  "#70",
  "Part 3",
  "Thanks Giving Day, Vietnam",
  "Blu Bugatti",
  "Macau Guia Race Winner",
  "Pace Car Red",
  "Weissa ch Package",
  "Vielside",
  "Sketchy",
  "Pandem",
  "EVA RT",
  "Quantum of Solace",
  "MDX 2025 LE",
  "BASF Livery",
  "DEX",
  "Mickey Mouse",
  "Golden Eye",
  "You Only Live Twice",
  "Silhoutte",
  "Le Mans 1971",
  "Wayne Taylor Racing",
  "Kodo",
  "Auto Finesse",
  "Super Silhoutte,Fausto Racing #555",
  "Speed Racer",
  "Jetsons",
  "UPS",
  "Speedy Xpress",
  "F1",
];

/** make (lowercased) -> its models, most common first. */
export const MODELS_BY_MAKE: Record<string, string[]> = {
  ford: [
    "Mustang",
    "GT",
    "F150",
    "Escort",
    "Bronco",
    "Police Interceptor",
    "F-150",
    "Shelby",
    "F-650",
    "Interceptor",
    "GT40",
    "Ranger",
    "Fiesta",
    "E-Transit",
    "Excursion",
    "F100",
    "Focus",
    "1935",
    "Explorer",
    "Model A",
    "Tri Motor",
    "Truck",
    "RS200",
    "427 Fairlane",
    "Thunderbird",
    "Lo Boy",
    "Galaxie",
    "Tourino",
    "Capri",
    "Puma",
    "Torino",
  ],
  fantasy: [
    "Twin Tag",
    "Coupe Clip",
    "Decidedly Go",
    "Supercharged",
    "Kool Kombi",
    "Hako Type D",
    "Feline Lucky",
    "Quick Chat",
    "Long Bloc",
    "Ravenger S/T",
    "Hoto Roto",
    "Speed Driver",
    "RD-06",
    "Mod Mill",
    "Draggin' Wagon",
    "El Segundo Coupe",
    "Mod Rod",
    "Barbie Dream Camper",
    "Twin Mill",
    "Random",
    "Time Attaxi",
    "Dumpster",
    "Garbage Truck",
    "Quick Bite",
    "Rodger Dodger",
    "Disney Steamboat",
    "Gotto Go",
    "Surf n Turf",
    "Drift Ender",
    "Super Twin Mill",
    "Rroadster",
    "Terra Tractyle",
    "Pass 'n Go",
    "Twin Dorado",
    "Track Dwagon",
    "Kick Kart",
    "Drift'n Break",
    "Sushi Tuner",
    "Mo-Stash",
    "Monteracer",
    "HW Ultimate TRex Transporter",
    "Cart Racer",
    "Cool Combi",
    "Carbonator",
    "Rodger Dodger 2.0",
    "Mad Fast",
    "Street Wiener",
    "Pedal Driver",
    "Head Starter",
    "Donut Drifter",
    "Fleet Street",
    "Euro Hauler",
    "Flippin Fast",
    "Blaze Blaster II",
    "Max Steel",
    "Muscle and Blown",
    "Combat Medic",
    "Screamliner",
    "Ground Grinder",
    "Rally Finale",
    "Deora",
    "Sooo Fast",
    "Deora II",
    "2 Jet Z",
    "Celero GT",
    "El Segundo Coupe Clip",
    "Click Shift",
    "Rrroadster",
  ],
  "pop culture": [
    "Lightning McQueen",
    "Batmobile",
    "Pizza Planet Truck",
    "RC",
    "Mack",
    "Cow",
    "Hudson Hornet",
    "Guinevere Van",
    "The Simpsons Family Car",
    "Mater",
    "Francesco Bernoulli",
    "Miss Fritter",
    "Chic Hicks",
    "Sheriff",
    "Sarge",
    "The King",
    "Fillmore",
    "Luigi",
    "Guido",
    "Flo",
    "Lizzie",
    "Red",
    "Frank",
    "Sally Carrera",
    "Dinoco Helicopter",
    "Miles Axlerod",
    "Mac iCar",
    "Louis Hamilton",
    "Raoul ÇaRoule",
    "Jackson Storm Truck",
    "Jackson Storm",
    "Smokey",
    "Sterling",
    "Grem",
    "Tex Dinoco",
    "RSN Helicopter",
    "Cruz Ramirex",
    "Finn McMissile",
    "Ramone",
    "Snot Rod",
    "Wingo",
    "DJ",
    "Boost",
    "Salty",
    "River Flyer",
    "Airliner",
    "Optimus Prime",
    "Grumobile",
    "Scooby Doo Mystery Machine",
    "Reptar Wagon",
    "Mattel Dream Mobile",
    "Snoopy",
    "The Batman",
    "The Dark Knight",
    "Flintstone Flintmobile",
    "Mario Kart",
    "Packin' Pacer",
    "Mutt Cutts Van",
    "Dairy Delivery",
    "Harry Potter Hogwards Express",
    "BLVD Bruiser",
    "70s Van",
    "Armoured Truck",
    "Deadpool Scooter",
    "Airwolf Helicopter",
    "Buzz Lightyear",
    "Woody",
    "Jessie",
    "Space Alien",
    "Armoured Batmobile",
    "Mickey Mouse Car",
    "Mach 5",
    "Jetsons Capsule Car",
  ],
  toyota: [
    "Supra",
    "Land Cruiser",
    "Tacoma",
    "4Runner",
    "AE86",
    "FJ Cruiser",
    "Yaris",
    "Prius",
    "RAV4",
    "Altezza",
    "Century",
    "Alphard",
    "Celica",
    "Hilux",
    "GR86",
    "Tundra",
    "Off Road Truck",
    "86GT",
    "Soarer",
    "Hiace",
    "GR Yaris",
    "Alphard 40",
    "Vellfire",
    "2000GT",
    "TRD",
    "SR5",
  ],
  nissan: [
    "Skyline",
    "GT-R",
    "Silvia",
    "Z",
    "Ariya",
    "350Z",
    "Fairlady",
    "180SX",
    "Primera",
    "Sentra",
    "300ZX",
    "35GT",
    "Nismo",
    "Patrol",
    "GTRR",
  ],
  porsche: [
    "911",
    "914",
    "917",
    "918",
    "Carrera",
    "Panamera Turbo",
    "718",
    "934",
    "Taycan",
    "928S",
    "930",
    "550",
    "904",
    "Porsche 911 Convoy",
    "Panamera",
    "993",
    "356",
    "Tatcan",
    "906",
    "944",
    "Cayenne",
  ],
  chevrolet: [
    "Camaro",
    "Corvette",
    "Silverado",
    "Stock Car",
    "Impala",
    "Chevelle",
    "Chevelle SS",
    "Nova",
    "Caprice",
    "Fleetline",
    "Blazer",
    "Monte Carlo",
    "Z06",
    "K1500",
    "Tahoe",
    "Pontiac",
    "C-10",
    "57",
    "Blazed",
    "Chevy II",
    "K5",
    "Corvair",
    "Ramp Truck",
    "Super Nova",
    "El Camino",
    "Bel Air",
  ],
  bmw: [
    "M3",
    "M4",
    "M5",
    "i4",
    "M2",
    "2002",
    "Z8",
    "365",
    "1M",
    "7 Series",
    "318",
    "X5M",
    "733i",
    "i7",
    "CSL",
    "M1",
    "i8",
    "835",
    "507",
    "750IL",
    "Alpine",
    "M850i",
    "E30",
    "Z3",
    "3 Series",
    "Z4M",
    "K1300R",
    "$ nineT Racer",
  ],
  "mercedes benz": [
    "190E",
    "A35",
    "S680",
    "W16",
    "SL63",
    "Unimog",
    "Sprinter",
    "CLK 63",
    "Actros",
    "CLK-GTR",
    "500E",
    "G63",
    "GT63",
    "GLC63S",
    "CLE S3",
    "SLC",
    "300 SEL",
    "E Class",
    "FW-48",
    "F1",
    "MCL40",
    "230 SL",
    "G550",
    "450",
    "G Wagon",
    "Sprinter Ambulance",
    "300 SL",
    "G Class",
    "SLS AMG Coupe",
    "A-Class",
    "300 SLR",
    "PennTransporter",
    "AMG",
    "CLS63",
    "GT3",
    "G-63",
    "EQS 53",
    "500 SEC",
    "500",
    "C63",
  ],
  honda: [
    "Civic",
    "S2000",
    "E",
    "Motocompo",
    "CB750",
    "S800",
    "City",
    "NSX-R",
    "RBPTH002",
    "NSX",
    "VFR750R",
    "Ridgeline",
    "Super Cub",
    "City Turbo II",
    "Del Sol",
    "N600",
    "Monkey Z50",
  ],
  lamborghini: [
    "Huracan",
    "Countach",
    "Aventador",
    "Revuelto",
    "Gallardo",
    "Miura",
    "Murcielaglo",
    "Sian",
    "Murcielago",
    "Urus",
    "LM002",
    "Centenario",
    "Temerario",
    "Aventedor",
  ],
  ferrari: [
    "F40",
    "250",
    "SF90",
    "VF-25",
    "LaFerrari",
    "12Cilindri",
    "Enzo",
    "512",
    "365 GTD",
    "SF25",
    "F355",
    "Testarossa",
    "206 GT",
    "Purosangue",
    "Daytona",
    "Dino 246",
    "S85",
    "GTC4Lusso",
    "F50",
    "499P",
  ],
  dodge: [
    "Charger",
    "Challenger",
    "Viper",
    "Durango",
    "Hemi",
    "Dart",
    "Coronet",
    "V-Series Truck",
    "Li'l Red",
    "D-200",
  ],
  "aston martin": [
    "Vantage",
    "DB5",
    "DBS",
    "Vanquish",
    "Vulcan",
    "DB10",
    "DB9",
    "DBR1",
    "Valkyrie",
    "GT3",
    "Valhalla",
    "Vantage V8",
    "GT350",
  ],
  jeep: [
    "Wrangler",
    "Gladiator",
    "Willy",
    "J10",
    "Wagoneer",
    "Grand Cherokee",
    "Cherokee",
    "Avenger",
    "Recon",
    "Commando",
    "Renegade",
    "4x4",
  ],
  audi: [
    "R8",
    "RS5",
    "Quattro",
    "RS",
    "90",
    "A6",
    "RS 8",
    "S4",
    "Sauber",
    "R8 Spyder",
    "Sport",
    "A4",
    "RS4",
  ],
  volkswagen: [
    "T3",
    "Beetle",
    "T20",
    "ID",
    "Classic Bug",
    "Squareback",
    "Golf",
    "ID.Buzz",
    "T1",
    "Van",
    "Type 2 Bus",
    "Golf GTI",
    "Jetta",
    "Corrado",
    "T28",
  ],
  mazda: ["RX-7", "RX3", "Repu", "AutoZam", "323", "MX-5", "Miata"],
  mbx: [
    "Tangiers",
    "Lil Dumper",
    "Excavator",
    "Crop Duster",
    "EV Trashtruck",
    "EV School Bus",
    "Sky Cruiser",
    "Backhoe",
    "Baja Bandit",
    "Swamp Raider",
    "Rescue Helicopter",
    "Bucket Tipper",
    "Load Lifter",
    "Field Car",
    "Trash Truck",
    "Crop Sprayer",
    "Flame Blaster",
    "Cement Mixer",
  ],
  mclaren: [
    "F1",
    "W1",
    "P1",
    "Senna",
    "720S",
    "MP4/4",
    "Formula E",
    "Speedtail",
    "765LT",
    "GTS",
    "Solus",
  ],
  "land rover": ["Defender", "6x6", "Discovery", "Gen II", "S2", "Defender 110"],
  subaru: ["Imprezza", "BRZ", "WRX", "Legacy", "Outback", "Crosstrek", "Brat", "WRX S4"],
  jaguar: ["C-X75", "F-Type", "MK1", "XJC", "E Type", "XKR", "XK140", "E-Type", "XJS"],
  mitsubishi: ["Eclipse", "Lancer", "Pajero", "Lancer Evolution"],
  pontiac: ["Firebird", "GTO", "Aztec", "Bonneville"],
  tesla: ["Model X", "Cybertruck", "Roadster", "Model Y", "Cyberquad"],
  "alfa romeo": ["Giulia", "GTV6", "Duetto", "4C", "Tonale"],
  hyundai: ["Concept N Vision 72", "i20", "Ioniq 5 N", "Ionic 6", "Ionic 5", "Velostar"],
  lotus: ["Espirit", "Type 49", "Evija", "Cortina"],
  bentley: ["Batur", "Flying Spur", "Continental GT", "Bentayga", "Mulliner", "Bacalar"],
  bugatti: ["Bolide", "Chiron", "Divo", "Ebtio", "EB110", "Veyron"],
  dmc: ["DeLorean"],
  fiat: ["642 Transporter", "500X", "500", "Topolino", "500D", "Beast of Turin"],
  gmc: ["Cyclone", "3500 Utility Truck", "Sierra", "C8500", "T8500", "Hummer", "Panel Van", "3500"],
  ducati: ["DesertX", "Scrambler", "1098", "Panigale", "63"],
  maserati: ["Shamal", "MC20", "Grantourismo", "MC 12", "MC12"],
  cadillac: [
    "Project GTP",
    "ATS-V R",
    "Celestiq",
    "Fleetwood",
    "CT5-V",
    "Coupe DeVille",
    "V-Series",
  ],
  pagani: ["Zonda", "Utopia", "Zonda Cinque", "Huayra"],
  "range rover": ["Classic", "Phev", "Velar", "Evoque", "1981", "1971"],
  citroen: ["C3", "DS 21", "Hy", "eC4", "2CV"],
  renault: ["Espace", "Sport", "Megene", "Megane"],
  suzuki: ["Carry", "Swift", "Jimny"],
  volvo: ["240", "XC40", "Truck", "240 GL"],
  austin: ["Mini", "Mini Cooper"],
  lexus: ["LFA", "ES 300 H", "LC 500", "RC F", "ES300h"],
  batmobile: ["The Dark Knight", "TV Series", "Bat Copter"],
  datsun: ["260Z", "King Cab", "510", "Fairlady"],
  triumph: ["Scambler", "TR6", "Tiger", "Scrambler"],
  plymouth: ["Barracuda", "Superbird", "Road Runner"],
  ram: ["Ambulance", "1500"],
  lancia: ["Stratos", "Delta", "Rally 037"],
  ingen: ["Off Road Vehicle", "Mission Team", "Rapid Rescue"],
  acura: ["Integra", "NSX", "Legend"],
  buick: ["Regal", "Rivera", "Roadmaster", "Skylark"],
  mini: ["Cooper", "Aceman", "Cooper S"],
  masito: ["Highway Haulers"],
  "monster truck": ["Burger", "Hotwheels Monster Truck", "Yellow"],
  lincoln: ["Continental", "Capri"],
  polaris: ["RZR Pro", "RZR", "Ranger EV"],
  pierce: ["Volterra EV", "Quantum"],
  shelby: ["Cobra", "GT350"],
  alpine: ["A526", "A110R"],
  koenigsegg: ["CC850", "Gamera", "Agera R"],
  isuzu: ["DMax", "N"],
  man: ["TGL", "TGXXXL"],
  polestar: ["TRX"],
  "w motors": ["Lykan"],
  plymoth: ["Road Runner", "Duster"],
  skidster: ["Construction"],
  scania: ["XT"],
  "ground grinder": ["Construction"],
  "blaze blaster iii": ["Fire Truck"],
  hummer: ["H1", "H2"],
  peugeot: ["508", "205"],
  boeing: ["747-400", "F/A-18"],
  airbus: ["Beluga", "Helicopters"],
  freightliner: ["M2"],
  intrenational: ["Durastar"],
  "fendt 209 varlo": ["209 Varlo"],
  lner: ["Class J50"],
  "deutz-fahr": ["9390 TTV"],
  "massey ferguson": ["8737"],
  "seven plank": ["Green Troublesome Truck"],
  piaggio: ["Vespa"],
  maisto: ["Van"],
  panther: ["De Ville"],
  auburn: ["Speedster"],
  mcmurtry: ["Speirling"],
  "gordon murray automotive": ["T.33"],
  delorean: ["Alpha 5"],
  williams: ["FW47"],
  lucid: ["Air"],
  rover: ["SDI"],
  "land cruiser": ["Prado"],
  rimac: ["Nevera"],
  dacia: ["Duster"],
  batman: ["Bat Boat"],
  opel: ["Astra"],
  transformers: ["Optimus Prime"],
  hudson: ["Hornet"],
  hirohata: ["Merc"],
  mario: ["Circuit Special"],
  luigi: ["Circuit Special"],
  radical: ["SR3"],
  sherp: ["N"],
  "automibili pikinfarina": ["Ballista"],
  "f-35 b": ["Lightning II"],
  spaceshuttle: ["Orbiter"],
  airblade: ["Helicopter"],
  "western star": ["6900 XD"],
  trabant: ["P 601"],
  holden: ["VF-25"],
  alpha: ["Wolf"],
  international: ["Durastar"],
  abarth: ["595"],
  cirrus: ["SF50"],
  cessna: ["172"],
  "lockheed martin": ["C-130 J"],
  ups: ["Delivery Tuck"],
  morris: ["Mini Cooper"],
  dhl: ["Delivery Van"],
  fossil: ["Transporter"],
  "speed racer": ["Mach 5"],
  celica: ["Red"],
  pontoon: ["Raft"],
  hino: ["300"],
  "rob'n": ["Pinks"],
  greenwood: ["Corvette"],
  motorcycle: ["Cruiser"],
  autocar: ["ASX"],
  hotwheels: ["F1 Concept"],
};

/** "make|model" (both lowercased) -> its variants, most common first. */
export const VARIANTS_BY_MODEL: Record<string, string[]> = {
  "ford|mustang": [
    "Dark Horse",
    "Fastback",
    "Boss 302",
    "Mach 1",
    "SVO",
    "Police",
    "Fastback 2+2",
    "Convertible",
    "GT",
    "Coupe",
    "RTR Spec 5-FD",
    "RTR Spec 5",
    "Mack 1",
    "Mach E 1400",
    "GTD",
    "GTE",
    "GT350",
    "GT Dark Horse",
    "Shelby GT500",
    "GT3",
    "SVT Cobra",
    "M1",
    "Shelby GT350",
  ],
  "ford|f150": ["Raptor", "SVT Lightning", "Lightning"],
  "ford|escort": ["RS1600", "BS1600", "RS 2000", "MKII RS 1800"],
  "ford|bronco": ["R"],
  "ford|police interceptor": ["Police Car"],
  "ford|f-150": ["Raptor", "Sandblaster", "SVT Raptor", "SVT Lightning"],
  "ford|shelby": ["GT500", "Cobra"],
  "ford|f-650": ["Rollback Plateau"],
  "ford|interceptor": ["Utility"],
  "ford|gt40": ["Mk IV"],
  "ford|ranger": ["Prerunner", "Raptor"],
  "ford|fiesta": ["MK2"],
  "ford|f100": ["Ranger"],
  "ford|focus": ["RS"],
  "ford|tourino": ["Talladega"],
  "ford|puma": ["Rally"],
  "ford|torino": ["Cobra"],
  "pop culture|pizza planet truck": ["Wooden", "OG", "The Good Dinosaur"],
  "pop culture|rc": ["Toy Story"],
  "toyota|supra": ["GR", "JZA80", "GT300", "GT300 A80", "A80"],
  "toyota|land cruiser": ["FJ60", "Prado", "80", "78", "70 Series", "250"],
  "toyota|tacoma": ["TRD Pro"],
  "toyota|4runner": ["TRD Pro"],
  "toyota|ae86": ["Sprint Trueno", "RWB"],
  "toyota|yaris": ["GR Rally 2", "GRMN"],
  "toyota|rav4": ["TRD", "Off Road"],
  "toyota|alphard": ["40"],
  "toyota|celica": ["GT-Four RC"],
  "toyota|hilux": ["SR5 Pickup", "Pickup"],
  "toyota|trd": ["3000GT"],
  "toyota|sr5": ["Xtra Cab"],
  "nissan|skyline": [
    "GT-R",
    "R34",
    "GT-R (R32)",
    "Kenmeri",
    "2000GT-R",
    "GT-R (R34)",
    "HT 2000 GT-R",
    "2000",
    "GT-R (R32) Pandem",
    "GT-R V.Spec R (BNR34)",
    "GT-R NT 2000",
    "GT-R R32 Kaido House",
    "GT-R V-Spec II Nur",
    "GT-R V-Spec II",
    "R32 Widebody",
    "R32 GTR",
    "GTR",
  ],
  "nissan|gt-r": ["R35", "Nismo", "Nismo GT3", "GT3 Nismo"],
  "nissan|silvia": ["S15", "S13", "Spec Aero", "S51", "S15 Spec R Aero"],
  "nissan|z": ["GT3500", "FFZ400", "GT500"],
  "nissan|ariya": ["Pole to Pole", "Pole To Pole EV"],
  "nissan|fairlady": ["Z"],
  "nissan|180sx": ["Type X"],
  "nissan|300zx": ["Twin Turbo"],
  "nissan|35gt": ["RR"],
  "nissan|nismo": ["270R (S14)"],
  "nissan|gtrr": ["R35"],
  "porsche|911": [
    "Carrera",
    "GT3 R",
    "GT3 RS",
    "Rally",
    "Carrera Cabriolet",
    "Carrera GTO",
    "Carrera T",
    "Targa",
    "Carrera S",
    "Turbo 3.6",
    "R",
    "Carrera RS27",
    "Carrera RS38",
    "GT3 (Cup) 992",
    "Carrera GT3",
    "GT3",
    "GT2 RS",
    "(992) GT3 RS",
    "GT3 Touring",
    "GT3 R (922)",
    "GT3 R (992)",
    "GT1",
  ],
  "porsche|914": ["Safari"],
  "porsche|917": ["KH", "K"],
  "porsche|918": ["Spyder"],
  "porsche|carrera": ["GT"],
  "porsche|panamera turbo": ["Police"],
  "porsche|718": ["Boxter", "Spyder RS"],
  "porsche|taycan": ["Turbo S EV", "GTS Sport"],
  "porsche|928s": ["Safari"],
  "porsche|930": ["RWB", "Turbo"],
  "porsche|550": ["Spyder"],
  "porsche|904": ["Carrera GTS"],
  "porsche|panamera": ["Turbo SE"],
  "porsche|993": ["GT2"],
  "porsche|356": ["Outlaw"],
  "porsche|tatcan": ["Turbo S"],
  "porsche|906": ["Carrera 6"],
  "porsche|944": ["Turbo"],
  "chevrolet|camaro": ["SS", "SS 296", "ZL1", "Off Road", "Copa"],
  "chevrolet|corvette": ["Gasser", "Stingray", "ZR-1", "Grand Sport", "Z06 GT3R 4", "COPO"],
  "chevrolet|silverado": ["PPV Truck", "Trail Boss"],
  "chevrolet|impala": ["Lowrider"],
  "chevrolet|chevelle": ["SS"],
  "chevrolet|chevelle ss": ["Wagon"],
  "chevrolet|nova": ["Station Wagon"],
  "chevrolet|z06": ["Spider"],
  "chevrolet|k1500": ["Pickup"],
  "chevrolet|tahoe": ["Z71"],
  "chevrolet|pontiac": ["Firebird"],
  "chevrolet|blazed": ["EV"],
  "chevrolet|k5": ["Blazer"],
  "chevrolet|corvair": ["Yenko Stinger"],
  "bmw|m3": ["Wagon", "GTR", "GTR E46"],
  "bmw|m4": ["GT3", "M-Performance", "GT3 EVO 1", "GT3 Evo"],
  "bmw|m5": ["Touring"],
  "bmw|i4": ["Police", "Police Sedan", "Police Car"],
  "bmw|318": ["TI"],
  "bmw|x5m": ["Competition"],
  "bmw|i8": ["Roadster"],
  "bmw|alpine": ["B7"],
  "bmw|3 series": ["Touring"],
  "mercedes benz|190e": ["E2.5 Evo II", "2.5 Evo II"],
  "mercedes benz|a35": ["AMG"],
  "mercedes benz|s680": ["Maybach"],
  "mercedes benz|w16": ["Petronas"],
  "mercedes benz|sl63": ["AMG"],
  "mercedes benz|unimog": ["1300L", "406"],
  "mercedes benz|sprinter": ["Ambulance"],
  "mercedes benz|clk 63": ["AMG"],
  "mercedes benz|g63": ["AMG"],
  "mercedes benz|gt63": ["AMG"],
  "mercedes benz|glc63s": ["AMG"],
  "mercedes benz|cle s3": ["AMG"],
  "mercedes benz|slc": ["Rallye"],
  "mercedes benz|300 sel": ["AMG"],
  "mercedes benz|e class": ["All Terrain"],
  "mercedes benz|450": ["SEL"],
  "mercedes benz|sls amg coupe": ["Black Series"],
  "mercedes benz|amg": ["GT"],
  "mercedes benz|cls63": ["4Matic AMG"],
  "mercedes benz|gt3": ["AMG"],
  "mercedes benz|g-63": ["AMG G Wagon"],
  "mercedes benz|eqs 53": ["AMG"],
  "mercedes benz|500 sec": ["AMG"],
  "mercedes benz|500": ["SEL"],
  "honda|civic": ["Type R", "Pandem", "Type R EK9", "Custom", "EG", "EK9", "S1", "Coupe EX EJI"],
  "honda|s2000": ["20th Anniversary"],
  "honda|city": ["Turbo II"],
  "honda|rbpth002": ["Oracle Redbull Racing", "Red Bull Racing RB20"],
  "honda|nsx": ["Type S", "Type-R"],
  "lamborghini|huracan": ["LP 610-4", "GT", "GT3 EVO2", "Sterrato", "Avio", "GT3 EVO", "GT3"],
  "lamborghini|countach": ["LPI 800-4", "LP5000 QV", "LP400S", "LP 5000 QV", "500S"],
  "lamborghini|aventador": ["Roadster"],
  "lamborghini|gallardo": ["LP 570-4 Superlggara", "Police"],
  "lamborghini|miura": ["P400 S"],
  "lamborghini|murcielaglo": ["Advan Racing", "Fighter"],
  "lamborghini|sian": ["FKP 37"],
  "lamborghini|murcielago": ["GT Evo"],
  "lamborghini|centenario": ["Roadster"],
  "ferrari|f40": ["Competizione"],
  "ferrari|250": ["GTO", "Testa Rossa"],
  "ferrari|sf90": ["Stradale"],
  "ferrari|512": ["TR"],
  "ferrari|365 gtd": ["Competizione"],
  "ferrari|sf25": ["Ferrari - HP"],
  "ferrari|daytona": ["SP3"],
  "ferrari|dino 246": ["GT"],
  "ferrari|s85": ["6794C"],
  "dodge|charger": ["Daytona", "RT", "Hellcat", "Pursuit", "R/T"],
  "dodge|challenger": ["Daytona", "SRT", "SRT Demon", "SRT Jailbreak", "RT"],
  "dodge|viper": ["GTS", "SRT"],
  "dodge|hemi": ["Challenger"],
  "dodge|coronet": ["Superbee"],
  "dodge|li'l red": ["Express Truck"],
  "aston martin|vantage": ["GT3", "GT8", "GTE", "V8"],
  "jeep|wrangler": ["Superlift", "4x4", "#18", "4XE"],
  "jeep|willy": ["MB"],
  "jeep|j10": ["Stepside"],
  "jeep|cherokee": ["Trackhawk", "Sport"],
  "audi|r8": ["LMS", "Taxi"],
  "audi|rs5": ["Coupe", "Sportsback"],
  "audi|quattro": ["Quattro"],
  "audi|rs": ["e-tron GT"],
  "audi|90": ["Quattro"],
  "audi|rs 8": ["Avant"],
  "audi|s4": ["Quattro"],
  "audi|sport": ["Quattro"],
  "audi|a4": ["Touring"],
  "volkswagen|t3": ["Wagon"],
  "volkswagen|beetle": ["4x4", "Convertible", "Classic"],
  "volkswagen|t20": ["Bus"],
  "volkswagen|id": ["Buzz Bomb", "Buzz"],
  "volkswagen|golf": ["MK1"],
  "volkswagen|t1": ["Microbus"],
  "volkswagen|jetta": ["Mk3"],
  "volkswagen|corrado": ["VRS"],
  "volkswagen|t28": ["Bus"],
  "mazda|rx-7": ["Drift", "Spirit R", "FD3S"],
  "mazda|323": ["GTR"],
  "mazda|mx-5": ["Miata"],
  "mazda|miata": ["MX-5"],
  "mbx|tangiers": ["Tuk Tuk"],
  "mbx|field car": ["Convertible"],
  "mbx|trash truck": ["EV"],
  "mclaren|f1": ["GTR", "GGT"],
  "mclaren|senna": ["GTR"],
  "mclaren|formula e": ["NOEM"],
  "mclaren|solus": ["0"],
  "land rover|defender": ["90", "Double Cab", "110"],
  "land rover|discovery": ["110"],
  "subaru|imprezza": ["22B-STi Version", "WRZ", "WRX Type R STI Version 30"],
  "subaru|brz": ["Pandem"],
  "subaru|wrx": ["S4 STI"],
  "subaru|legacy": ["RS", "GT (BP)"],
  "subaru|outback": ["Wilderness"],
  "subaru|wrx s4": ["STI"],
  "jaguar|f-type": ["Project 7"],
  "jaguar|xjc": ["V12 Coupe"],
  "jaguar|e type": ["Lightweight"],
  "jaguar|xk140": ["Roadster"],
  "mitsubishi|lancer": ["Evolution", "Evolution VI"],
  "mitsubishi|pajero": ["Evolution"],
  "pontiac|gto": ["Judge"],
  "alfa romeo|giulia": ["T1 Super"],
  "alfa romeo|gtv6": ["3.0", "30"],
  "hyundai|ionic 6": ["N Performance"],
  "hyundai|ionic 5": ["N Performance"],
  "hyundai|velostar": ["N Performance"],
  "lotus|espirit": ["Turbo", "S1"],
  "bentley|batur": ["Bonneville"],
  "bentley|flying spur": ["Hybrid"],
  "bentley|mulliner": ["Bacalar"],
  "bugatti|chiron": ["Pur Sport"],
  "bugatti|eb110": ["GT"],
  "bugatti|veyron": ["16.4 SuperSport"],
  "dmc|delorean": ["Time Machine", "12"],
  "gmc|sierra": ["3500 Wrecker"],
  "gmc|c8500": ["Topkick Tree Trimmer"],
  "gmc|t8500": ["Airport Service Truck"],
  "gmc|hummer": ["EV"],
  "gmc|3500": ["Attenuator Truck"],
  "ducati|panigale": ["V4"],
  "maserati|grantourismo": ["Folgore"],
  "cadillac|fleetwood": ["Series 60"],
  "pagani|zonda": ["F Rosso", "R"],
  "pagani|huayra": ["Roadster"],
  "renault|espace": ["F1"],
  "renault|sport": ["R.S. 01", "RS 01"],
  "renault|megane": ["Trophy"],
  "suzuki|swift": ["Sport"],
  "volvo|240": ["Drift Wagon"],
  "volvo|240 gl": ["Estate"],
  "austin|mini": ["Cooper S", "Van"],
  "austin|mini cooper": ["S"],
  "lexus|rc f": ["GT3"],
  "datsun|king cab": ["Baja"],
  "datsun|fairlady": ["2000"],
  "triumph|tiger": ["100"],
  "plymouth|barracuda": ["Formula S"],
  "ram|1500": ["REV", "Rebel"],
  "lancia|stratos": ["Zero"],
  "lancia|delta": ["L4", "HF Integrale Evoluzione"],
  "ingen|mission team": ["Petrol Craft"],
  "acura|integra": ["Type S HRC", "Type R", "Type-R"],
  "acura|legend": ["Coupe"],
  "buick|roadmaster": ["Estate"],
  "buick|skylark": ["Convertible"],
  "mini|aceman": ["SE"],
  "mini|cooper s": ["Cabrio"],
  "polaris|rzr pro": ["R4 Sport"],
  "pierce|volterra ev": ["Firetruck"],
  "pierce|quantum": ["Aeriel Ladder"],
  "shelby|cobra": ["477"],
  "w motors|lykan": ["Hypersport"],
  "scania|xt": ["Firetruck"],
  "hummer|h2": ["Limosine"],
  "peugeot|508": ["SW"],
  "peugeot|205": ["GTI 1.9"],
  "boeing|f/a-18": ["Super Hornet"],
  "airbus|helicopters": ["H130"],
  "freightliner|m2": ["106 Sattelite Truck", "106 Plus Crew"],
  "intrenational|durastar": ["Box Truck"],
  "piaggio|vespa": ["SS"],
  "williams|fw47": ["Williams"],
  "rover|sdi": ["Vittese"],
  "radical|sr3": ["XXR"],
  "sherp|n": ["1200"],
  "western star|6900 xd": ["Wrecker"],
  "holden|vf-25": ["Comodore SSV"],
  "alpha|wolf": ["Electric Truck"],
  "international|durastar": ["4400"],
  "cirrus|sf50": ["Vision Jet"],
  "cessna|172": ["Skyhawk"],
  "lockheed martin|c-130 j": ["Super Hercules"],
  "hino|300": ["Pandem"],
  "autocar|asx": ["Garbage Truck"],
};
