/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PreordersRouteImport } from './routes/preorders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiCarImagesRouteImport } from './routes/api/car-images'
import { Route as ApiCatalogOwnersRouteImport } from './routes/api/catalog-owners'
import { Route as ApiScanCarRouteImport } from './routes/api/scan-car'
import { Route as ApiSyncCatalogCarRouteImport } from './routes/api/sync-catalog-car'
import { Route as ApiSyncImagesRouteImport } from './routes/api/sync-images'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPushConfigRouteImport } from './routes/api/push/config'
import { Route as ApiPushDecideRouteImport } from './routes/api/push/decide'
import { Route as ApiPushNewUserRouteImport } from './routes/api/push/new-user'
import { Route as ApiPushTestRouteImport } from './routes/api/push/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PreordersRoute = PreordersRouteImport.update({
  id: '/preorders',
  path: '/preorders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCarImagesRoute = ApiCarImagesRouteImport.update({
  id: '/api/car-images',
  path: '/api/car-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogOwnersRoute = ApiCatalogOwnersRouteImport.update({
  id: '/api/catalog-owners',
  path: '/api/catalog-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanCarRoute = ApiScanCarRouteImport.update({
  id: '/api/scan-car',
  path: '/api/scan-car',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncCatalogCarRoute = ApiSyncCatalogCarRouteImport.update({
  id: '/api/sync-catalog-car',
  path: '/api/sync-catalog-car',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncImagesRoute = ApiSyncImagesRouteImport.update({
  id: '/api/sync-images',
  path: '/api/sync-images',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPushConfigRoute = ApiPushConfigRouteImport.update({
  id: '/api/push/config',
  path: '/api/push/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushDecideRoute = ApiPushDecideRouteImport.update({
  id: '/api/push/decide',
  path: '/api/push/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushNewUserRoute = ApiPushNewUserRouteImport.update({
  id: '/api/push/new-user',
  path: '/api/push/new-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/api/push/test',
  path: '/api/push/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/collection': typeof CollectionRoute
  '/duplicates': typeof DuplicatesRoute
  '/favourites': typeof FavouritesRoute
  '/habits': typeof HabitsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/preorders': typeof PreordersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/car-images': typeof ApiCarImagesRoute
  '/api/catalog-owners': typeof ApiCatalogOwnersRoute
  '/api/scan-car': typeof ApiScanCarRoute
  '/api/sync-catalog-car': typeof ApiSyncCatalogCarRoute
  '/api/sync-images': typeof ApiSyncImagesRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/decide': typeof ApiPushDecideRoute
  '/api/push/new-user': typeof ApiPushNewUserRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/collection': typeof CollectionRoute
  '/duplicates': typeof DuplicatesRoute
  '/favourites': typeof FavouritesRoute
  '/habits': typeof HabitsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/preorders': typeof PreordersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/car-images': typeof ApiCarImagesRoute
  '/api/catalog-owners': typeof ApiCatalogOwnersRoute
  '/api/scan-car': typeof ApiScanCarRoute
  '/api/sync-catalog-car': typeof ApiSyncCatalogCarRoute
  '/api/sync-images': typeof ApiSyncImagesRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/decide': typeof ApiPushDecideRoute
  '/api/push/new-user': typeof ApiPushNewUserRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/collection': typeof CollectionRoute
  '/duplicates': typeof DuplicatesRoute
  '/favourites': typeof FavouritesRoute
  '/habits': typeof HabitsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/preorders': typeof PreordersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/car-images': typeof ApiCarImagesRoute
  '/api/catalog-owners': typeof ApiCatalogOwnersRoute
  '/api/scan-car': typeof ApiScanCarRoute
  '/api/sync-catalog-car': typeof ApiSyncCatalogCarRoute
  '/api/sync-images': typeof ApiSyncImagesRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/decide': typeof ApiPushDecideRoute
  '/api/push/new-user': typeof ApiPushNewUserRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/collection'
    | '/duplicates'
    | '/favourites'
    | '/habits'
    | '/inventory'
    | '/login'
    | '/mcp'
    | '/orders'
    | '/preorders'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/car-images'
    | '/api/catalog-owners'
    | '/api/scan-car'
    | '/api/sync-catalog-car'
    | '/api/sync-images'
    | '/.mcp/invoke-tool/$tool'
    | '/api/push/config'
    | '/api/push/decide'
    | '/api/push/new-user'
    | '/api/push/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/collection'
    | '/duplicates'
    | '/favourites'
    | '/habits'
    | '/inventory'
    | '/login'
    | '/mcp'
    | '/orders'
    | '/preorders'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/car-images'
    | '/api/catalog-owners'
    | '/api/scan-car'
    | '/api/sync-catalog-car'
    | '/api/sync-images'
    | '/.mcp/invoke-tool/$tool'
    | '/api/push/config'
    | '/api/push/decide'
    | '/api/push/new-user'
    | '/api/push/test'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/collection'
    | '/duplicates'
    | '/favourites'
    | '/habits'
    | '/inventory'
    | '/login'
    | '/mcp'
    | '/orders'
    | '/preorders'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/car-images'
    | '/api/catalog-owners'
    | '/api/scan-car'
    | '/api/sync-catalog-car'
    | '/api/sync-images'
    | '/.mcp/invoke-tool/$tool'
    | '/api/push/config'
    | '/api/push/decide'
    | '/api/push/new-user'
    | '/api/push/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  CollectionRoute: typeof CollectionRoute
  DuplicatesRoute: typeof DuplicatesRoute
  FavouritesRoute: typeof FavouritesRoute
  HabitsRoute: typeof HabitsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OrdersRoute: typeof OrdersRoute
  PreordersRoute: typeof PreordersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiCarImagesRoute: typeof ApiCarImagesRoute
  ApiCatalogOwnersRoute: typeof ApiCatalogOwnersRoute
  ApiScanCarRoute: typeof ApiScanCarRoute
  ApiSyncCatalogCarRoute: typeof ApiSyncCatalogCarRoute
  ApiSyncImagesRoute: typeof ApiSyncImagesRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPushConfigRoute: typeof ApiPushConfigRoute
  ApiPushDecideRoute: typeof ApiPushDecideRoute
  ApiPushNewUserRoute: typeof ApiPushNewUserRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preorders': {
      id: '/preorders'
      path: '/preorders'
      fullPath: '/preorders'
      preLoaderRoute: typeof PreordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/car-images': {
      id: '/api/car-images'
      path: '/api/car-images'
      fullPath: '/api/car-images'
      preLoaderRoute: typeof ApiCarImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog-owners': {
      id: '/api/catalog-owners'
      path: '/api/catalog-owners'
      fullPath: '/api/catalog-owners'
      preLoaderRoute: typeof ApiCatalogOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-car': {
      id: '/api/scan-car'
      path: '/api/scan-car'
      fullPath: '/api/scan-car'
      preLoaderRoute: typeof ApiScanCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-catalog-car': {
      id: '/api/sync-catalog-car'
      path: '/api/sync-catalog-car'
      fullPath: '/api/sync-catalog-car'
      preLoaderRoute: typeof ApiSyncCatalogCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-images': {
      id: '/api/sync-images'
      path: '/api/sync-images'
      fullPath: '/api/sync-images'
      preLoaderRoute: typeof ApiSyncImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/config': {
      id: '/api/push/config'
      path: '/api/push/config'
      fullPath: '/api/push/config'
      preLoaderRoute: typeof ApiPushConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/decide': {
      id: '/api/push/decide'
      path: '/api/push/decide'
      fullPath: '/api/push/decide'
      preLoaderRoute: typeof ApiPushDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/new-user': {
      id: '/api/push/new-user'
      path: '/api/push/new-user'
      fullPath: '/api/push/new-user'
      preLoaderRoute: typeof ApiPushNewUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/test': {
      id: '/api/push/test'
      path: '/api/push/test'
      fullPath: '/api/push/test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  CollectionRoute: CollectionRoute,
  DuplicatesRoute: DuplicatesRoute,
  FavouritesRoute: FavouritesRoute,
  HabitsRoute: HabitsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OrdersRoute: OrdersRoute,
  PreordersRoute: PreordersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiCarImagesRoute: ApiCarImagesRoute,
  ApiCatalogOwnersRoute: ApiCatalogOwnersRoute,
  ApiScanCarRoute: ApiScanCarRoute,
  ApiSyncCatalogCarRoute: ApiSyncCatalogCarRoute,
  ApiSyncImagesRoute: ApiSyncImagesRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPushConfigRoute: ApiPushConfigRoute,
  ApiPushDecideRoute: ApiPushDecideRoute,
  ApiPushNewUserRoute: ApiPushNewUserRoute,
  ApiPushTestRoute: ApiPushTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
