-- ---------------------------------------------------------------------------
-- tesoro_raw."SNO" came in with the spreadsheet import as a plain NOT NULL
-- integer with no default. Every write from the app goes through PostgREST's
-- upsert, which is INSERT ... ON CONFLICT DO UPDATE: Postgres validates the
-- proposed tuple against NOT NULL *before* the conflict resolves, so a payload
-- without SNO was rejected with
--
--   23502: null value in column "SNO" of relation "tesoro_raw"
--
-- for edits to existing rows as well as for new cars. The client now sends the
-- known SNO back on an edit; a brand new car has none, so the column needs a
-- default of its own.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  has_default boolean;
BEGIN
  SELECT (a.attidentity <> '' OR ad.adbin IS NOT NULL)
    INTO has_default
    FROM pg_attribute a
    LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
   WHERE a.attrelid = 'public.tesoro_raw'::regclass
     AND a.attname = 'SNO'
     AND a.attnum > 0
     AND NOT a.attisdropped;

  -- COALESCE(..., true) so a missing column leaves the table alone rather than
  -- erroring: this migration is a no-op on a database that already has one.
  IF NOT COALESCE(has_default, true) THEN
    ALTER TABLE public.tesoro_raw
      ALTER COLUMN "SNO" ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Start the sequence past every number the import already occupies, otherwise
-- the first generated SNO would collide with row 1.
-- pg_get_serial_sequence returns NULL when no sequence is attached, and setval
-- is strict, so this is safely inert in that case.
SELECT setval(
  pg_get_serial_sequence('public.tesoro_raw', 'SNO'),
  GREATEST((SELECT COALESCE(MAX("SNO"), 0) FROM public.tesoro_raw), 1),
  true
);
