// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
// Wraps brokeredPreviewStorage so "Remember me" can send the session to
// sessionStorage instead. The generated file itself is left alone.
import { rememberAwareStorage } from "./session-storage";
import { getSupabaseConfig } from "@/lib/supabase-config";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const TARGET_SUPABASE_URL = "https://matekrbcflojjooswoha.supabase.co";
const TARGET_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_t8mahOsDrNTnt-YeFGkgTA_ugnPJrpu";

function getSupabaseCredentials() {
  // 1. User custom configured Supabase connection (from UI configuration tab)
  if (typeof window !== "undefined") {
    const custom = getSupabaseConfig();
    if (custom.url && custom.key) {
      return { url: custom.url, key: custom.key };
    }
  }

  const envUrl = import.meta.env["VITE_SUPABASE_URL"];
  const envKey = import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"];

  // If env points to the auto-generated empty sandbox project 'pllpyzsfuhpsmqbxgarw' or is missing
  if (!envUrl || envUrl.includes("pllpyzsfuhpsmqbxgarw")) {
    return { url: TARGET_SUPABASE_URL, key: TARGET_SUPABASE_PUBLISHABLE_KEY };
  }

  // If pointing to the target matekrbcflojjooswoha project, ensure matching key
  if (envUrl.includes("matekrbcflojjooswoha")) {
    const isInvalidKey = !envKey || envKey.includes("u0YZRo_jk0YerMn96oj2OQ_KaKQCS5O");
    return {
      url: TARGET_SUPABASE_URL,
      key: isInvalidKey ? TARGET_SUPABASE_PUBLISHABLE_KEY : envKey,
    };
  }

  return {
    url: envUrl,
    key: envKey || TARGET_SUPABASE_PUBLISHABLE_KEY,
  };
}

function createSupabaseClient() {
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = getSupabaseCredentials();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      `[Supabase] Supabase environment variables are missing. Using in-memory fallback client.`,
    );
    const mockQueryBuilder = {
      select: () => mockQueryBuilder,
      insert: () => mockQueryBuilder,
      update: () => mockQueryBuilder,
      delete: () => mockQueryBuilder,
      eq: () => mockQueryBuilder,
      neq: () => mockQueryBuilder,
      order: () => mockQueryBuilder,
      single: async () => ({ data: null, error: null }),
      maybeSingle: async () => ({ data: null, error: null }),
      then: (resolve: (val: { data: null; error: null }) => void) =>
        Promise.resolve({ data: null, error: null }).then(resolve),
      catch: (reject: (err: unknown) => void) =>
        Promise.resolve({ data: null, error: null }).catch(reject),
    };

    return {
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        onAuthStateChange: () => ({
          data: {
            subscription: {
              id: "mock",
              callback: () => {},
              unsubscribe: () => {},
            },
          },
        }),
        getUser: async () => ({ data: { user: null }, error: null }),
      },
      from: () => mockQueryBuilder,
    } as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: rememberAwareStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export function resetSupabaseClient() {
  _supabase = undefined;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
